CREATE TEMP TABLE tmp (
    PARID text, 
    BORO text, 
    BLOCK text, 
    LOT text, 
    EASE text, 
    SUBIDENT_REUC text, 
    RECTYPE text, 
    AV_YEAR4 text, 
    IDENT text, 
    SUBIDENT text, 
    ROLL_SECTION text, 
    SECVOL text, 
    PYMKTLAND text, 
    PYMKTTOT text, 
    PYACTLAND text, 
    PYACTTOT text, 
    PYACTEXTOT text, 
    PYTRNLAND text, 
    PYTRNTOT text, 
    PYTRNEXTOT text, 
    PYTXBTOT text, 
    PYTXBEXTOT text, 
    PYTAXCLASS text, 
    TENMKTLAND text, 
    TENMKTTOT text, 
    TENACTLAND text, 
    TENACTTOT text, 
    TENACTEXTOT text, 
    TENTRNLAND text, 
    TENTRNTOT text, 
    TENTRNEXTOT text, 
    TENTXBTOT text, 
    TENTXBEXTOT text, 
    TENTAXCLASS text, 
    CBNMKTLAND text, 
    CBNMKTTOT text, 
    CBNACTLAND text, 
    CBNACTTOT text, 
    CBNACTEXTOT text, 
    CBNTRNLAND text, 
    CBNTRNTOT text, 
    CBNTRNEXTOT text, 
    CBNTXBTOT text, 
    CBNTXBEXTOT text, 
    CBNTAXCLASS text, 
    FINMKTLAND text, 
    FINMKTTOT text, 
    FINACTLAND text, 
    FINACTTOT text, 
    FINACTEXTOT text, 
    FINTRNLAND text, 
    FINTRNTOT text, 
    FINTRNEXTOT text, 
    FINTXBTOT text, 
    FINTXBEXTOT text, 
    FINTAXCLASS text, 
    CURMKTLAND text, 
    CURMKTTOT text, 
    CURACTLAND text, 
    CURACTTOT text, 
    CURACTEXTOT text, 
    CURTRNLAND text, 
    CURTRNTOT text, 
    CURTRNEXTOT text, 
    CURTXBTOT text, 
    CURTXBEXTOT text, 
    CURTAXCLASS text, 
    PERIOD text, 
    NEWDROP text, 
    NOAV text, 
    VALREF text, 
    BLDG_CLASS text, 
    AV_OWNER text, 
    ZONING text, 
    HOUSENUM_LO text, 
    HOUSENUM_HI text, 
    STREET_NAME text, 
    ZIP_CODE text, 
    GEOSUPPORT_RC text, 
    STCODE text, 
    LOT_FRT text, 
    LOT_DEP text, 
    LOT_IRREG text, 
    BLD_FRT text, 
    BLD_DEP text, 
    BLD_EXT text, 
    BLD_STORY text, 
    CORNER text, 
    LAND_AREA text, 
    NUM_BLDGS text, 
    YRBUILT text, 
    YRBUILT_RANGE text, 
    YRBUILT_FLAG text, 
    YRALT1 text, 
    YRALT1_RANGE text, 
    YRALT2 text, 
    YRALT2_RANGE text, 
    COOP_APTS text, 
    UNITS text, 
    REUC_REF text, 
    APTNO text, 
    COOP_NUM text, 
    CPB_BORO text, 
    CPB_DIST text, 
    APPT_DATE text, 
    APPT_BORO text, 
    APPT_BLOCK text, 
    APPT_LOT text, 
    APPT_EASE text, 
    CONDO_Number text, 
    CONDO_SFX1 text, 
    CONDO_SFX2 text, 
    CONDO_SFX3 text, 
    UAF_LAND text, 
    UAF_BLDG text, 
    PROTEST_1 text, 
    PROTEST_2 text, 
    PROTEST_OLD text, 
    ATTORNEY_GROUP1 text, 
    ATTORNEY_GROUP2 text, 
    ATTORNEY_GROUP_OLD text, 
    GROSS_SQFT text, 
    HOTEL_AREA_GROSS text, 
    OFFICE_AREA_GROSS text, 
    RESIDENTIAL_AREA_GROSS text, 
    RETAIL_AREA_GROSS text, 
    LOFT_AREA_GROSS text, 
    FACTORY_AREA_GROSS text, 
    WAREHOUSE_AREA_GROSS text, 
    STORAGE_AREA_GROSS text, 
    GARAGE_AREA text, 
    OTHER_AREA_GROSS text, 
    REUC_DESCRIPTION text, 
    EXTRACTDT text, 
    PYTAXFLAG text, 
    TENTAXFLAG text, 
    CBNTAXFLAG text, 
    FINTAXFLAG text,
    CURTAXFLAG text
);

\COPY tmp FROM PSTDIN WITH NULL AS '' DELIMITER E'\t' quote '"' CSV;

DROP TABLE IF EXISTS :NAME CASCADE;
SELECT 
    boro,
    block,
    lot,
    street_name,
    housenum_lo,
    housenum_hi,
    aptno,
    zip_code,
    bldg_class,
    ease,
    av_owner,
    land_area,
    gross_sqft,
    residential_area_gross,
    office_area_gross,
    retail_area_gross,
    garage_area,
    storage_area_gross,
    factory_area_gross,
    other_area_gross,
    num_bldgs,
    bld_story,
    coop_apts,
    units,
    lot_frt,
    lot_dep,
    bld_frt,
    bld_dep,
    bld_ext,
    lot_irreg,
    curactland,
    curacttot,
    curactextot,
    yrbuilt,
    yralt1,
    yralt2,
    condo_number,
    appt_boro,
    appt_block,
    appt_lot,
    appt_ease,
    appt_date,
    parid
INTO :NAME FROM tmp;