CREATE SCHEMA IF NOT EXISTS :NAME;
DROP TABLE IF EXISTS :NAME.:"VERSION" CASCADE;
SELECT * INTO :NAME.:"VERSION" FROM :NAME;

DROP VIEW IF EXISTS :NAME.latest;
CREATE VIEW :NAME.latest as (
    SELECT :"VERSION" as v, * 
    FROM :NAME.:"VERSION"
);

DROP TABLE :NAME;