DROP TABLE IF EXISTS export_pluto;
SELECT
	borough::varchar(2),
	trim(block)::numeric(10,0) as block,
	lot::numeric(5,0),
	cd::numeric(5,0),
	ct2010::varchar(7),
	cb2010::varchar(5),
	schooldist::varchar(3),
	council::numeric(5,0),
	zipcode::numeric(10,0),
	firecomp::varchar(4),
	policeprct::numeric(5,0),
	healthcenterdistrict::numeric(5,0),
	healtharea::numeric(5,0),
	sanitboro::varchar(2),
	SanitDistrict::varchar(2),
	sanitsub::varchar(2),
	address::varchar(39),
	zonedist1::varchar(9),
	zonedist2::varchar(9),
	zonedist3::varchar(9),
	zonedist4::varchar(9),
	overlay1::varchar(4),
	overlay2::varchar(4),
	spdist1::varchar(12),
	spdist2::varchar(12),
	spdist3::varchar(12),
	ltdheight::varchar(5),
	splitzone::varchar(1),
	bldgclass::varchar(2),
	landuse::varchar(2),
	easements::numeric(5,0),
	ownertype::varchar(1),
	ownername::varchar(85),
	lotarea::numeric(10,0),
	bldgarea::numeric(10,0),
	comarea::numeric(10,0),
	resarea::numeric(10,0),
	officearea::numeric(10,0),
	retailarea::numeric(10,0),
	garagearea::numeric(10,0),
	strgearea::numeric(10,0),
	factryarea::numeric(10,0),
	otherarea::numeric(10,0),
	areasource::varchar(1),
	numbldgs::numeric(10,0),
	numfloors::numeric(19,7),
	unitsres::numeric(10,0),
	unitstotal::numeric(10,0),
	lotfront::numeric(19,7),
	lotdepth::numeric(19,7),
	bldgfront::numeric(19,7),
	bldgdepth::numeric(19,7),
	ext::varchar(2),
	proxcode::varchar(1),
	irrlotcode::varchar(1),
	lottype::varchar(1),
	bsmtcode::varchar(1),
	assessland::numeric(19,5),
	assesstot::numeric(19,5),
	exempttot::numeric(19,5),
	yearbuilt::numeric(5,0),
	yearalter1::numeric(5,0),
	yearalter2::numeric(5,0),
	histdist::varchar(66),
	landmark::varchar(150),
	BuiltFAR::numeric(19, 11),
	ResidFAR::numeric(19, 11),
	CommFAR::numeric(19, 11),
	FacilFAR::numeric(19, 11),
	BoroCode::numeric(10,0),
	BBL::numeric(19,8),
	CondoNo::numeric(10,0),
	Tract2010::varchar(7),
	round(XCoord::numeric)::numeric(10,0) as XCoord,
	round(YCoord::numeric)::numeric(10,0) as YCoord,
	ZoneMap::varchar(3),
	ZMCode::varchar(1),
	Sanborn::varchar(8),
	TaxMap::varchar(5),
	EDesigNum::varchar(5),
	APPBBL::numeric(19,8),
	APPDate::varchar(10),
	PLUTOMapID::varchar(1),
	FIRM07_FLAG::varchar(1),
	PFIRM15_FLAG::varchar(1),
	Version::varchar(6),
	DCPEdited::varchar(3),
	latitude::numeric(19,7),
	Longitude::numeric(19,7),
	Notes::varchar(20)
INTO export_pluto
FROM pluto;

DROP TABLE IF EXISTS archive_pluto;
SELECT a.*, b.clipped_4326 as geom
INTO archive_pluto
FROM export_pluto a
LEFT JOIN pluto_geom b
on a.bbl::bigint = b.bbl::bigint;

DROP TABLE IF EXISTS unmapped;
SELECT
	a.borough as "Borough",
	a.block as "Block",
	a.lot::smallint as "Lot",
	a.cd::smallint as "CD",
	a.ct2010 as "CT2010",
	a.cb2010 as "CB2010",
	a.schooldist as "SchoolDist",
	a.council::smallint as "Council",
	a.zipcode as "ZipCode",
	a.firecomp as "FireComp",
	a.policeprct::smallint as "PolicePrct",
	a.healthcenterdistrict::smallint as "HealthCenterDistrict",
	a.healtharea::smallint as "HealthArea",
	a.sanitboro as "Sanitboro",
	a.sanitdistrict as "SanitDistrict",
	a.sanitsub as "SanitSub",
	a.address as "Address",
	a.zonedist1 as "ZoneDist1",
	a.zonedist2 as "ZoneDist2",
	a.zonedist3 as "ZoneDist3",
	a.zonedist4 as "ZoneDist4",
	a.overlay1 as "Overlay1",
	a.overlay2 as "Overlay2",
	a.spdist1 as "SPDist1",
	a.spdist2 as "SPDist2",
	a.spdist3 as "SPDist3",
	a.ltdheight as "LtdHeight",
	a.splitzone as "SplitZone",
	a.bldgclass as "BldgClass",
	a.landuse as "LandUse",
	a.easements::smallint as "Easements",
	a.ownertype as "OwnerType",
	a.ownername as "OwnerName",
	a.lotarea as "LotArea",
	a.bldgarea as "BldgArea",
	a.comarea as "ComArea",
	a.resarea as "ResArea",
	a.officearea as "OfficeArea",
	a.retailarea as "RetailArea",
	a.garagearea as "GarageArea",
	a.strgearea as "StrgeArea",
	a.factryarea as "FactryArea",
	a.otherarea as "OtherArea",
	a.areasource as "AreaSource",
	a.numbldgs as "NumBldgs",
	a.numfloors as "NumFloors",
	a.unitsres as "UnitsRes",
	a.unitstotal as "UnitsTotal",
	a.lotfront as "LotFront",
	a.lotdepth as "LotDepth",
	a.bldgfront as "BldgFront",
	a.bldgdepth as "BldgDepth",
	a.ext as "Ext",
	a.proxcode as "ProxCode",
	a.irrlotcode as "IrrLotCode",
	a.lottype as "LotType",
	a.bsmtcode as "BsmtCode",
	a.assessland as "AssessLand",
	a.assesstot as "AssessTot",
	a.exempttot as "ExemptTot",
	a.yearbuilt::smallint as "YearBuilt",
	a.yearalter1::smallint as "YearAlter1",
	a.yearalter2::smallint as "YearAlter2",
	a.histdist as "HistDist",
	a.landmark as "Landmark",
	a.builtfar as "BuiltFAR",
	a.residfar as "ResidFAR",
	a.commfar as "CommFAR",
	a.facilfar as "FacilFAR",
	a.borocode as "BoroCode",
	a.bbl as "BBL",
	a.condono as "CondoNo",
	a.tract2010 as "Tract2010",
	a.xcoord as "XCoord",
	a.ycoord as "YCoord",
	a.zonemap as "ZoneMap",
	a.zmcode as "ZMCode",
	a.sanborn as "Sanborn",
	a.taxmap as "TaxMap",
	a.edesignum as "EDesigNum",
	a.appbbl as "APPBBL",
	a.appdate as "APPDate",
	a.plutomapid as "PLUTOMapID",
	a.firm07_flag as "FIRM07_FLAG",
	a.pfirm15_flag as "PFIRM15_FLAG",
	a.version as "Version",
	a.dcpedited as "DCPEdited",
	a.latitude as "Latitude",
	a.longitude as "Longitude",
	a.notes as "Notes"
INTO unmapped 
FROM export_pluto a
WHERE bbl::bigint in (
	select bbl::bigint 
	from pluto 
	where geom is null);

ALTER TABLE unmapped ALTER COLUMN "Borough" SET NOT NULL;
ALTER TABLE unmapped ALTER COLUMN "Block" SET NOT NULL;
ALTER TABLE unmapped ALTER COLUMN "Lot" SET NOT NULL;
ALTER TABLE unmapped ALTER COLUMN "BBL" SET NOT NULL;
ALTER TABLE unmapped ALTER COLUMN "BoroCode" SET NOT NULL;