DELETE FROM dcp_pluto.qaqc_null
WHERE pair = :'VERSION'||' - '||:'VERSION_PREV' 
AND CONDO::boolean = :CONDO
AND MAPPED::boolean = :MAPPED;

INSERT INTO dcp_pluto.qaqc_null (
SELECT
    :'VERSION'||' - '||:'VERSION_PREV' as pair, 
	:CONDO as condo,
    :MAPPED as mapped,
    count(*) as total,
    count(nullif(a.borough IS NULL AND b.borough IS NOT NULL, true)) as borough,
    count(nullif(a.block IS NULL AND b.block IS NOT NULL, true)) as block,
    count(nullif(a.lot IS NULL AND b.lot IS NOT NULL, true)) as lot,
    count(nullif(a.cd IS NULL AND b.cd IS NOT NULL, true) as cd,
    count(nullif(a.ct2010 IS NULL AND b.ct2010 IS NOT NULL, true) as ct2010,
    count(nullif(a.cb2010 IS NULL AND b.cb2010 IS NOT NULL, true) as cb2010,
    count(nullif(a.schooldist IS NULL AND b.schooldist IS NOT NULL, true) as schooldist,
    count(nullif(a.council IS NULL AND b.council IS NOT NULL, true) as council,
    count(nullif(a.zipcode IS NULL AND b.zipcode IS NOT NULL, true) as zipcode,
    count(nullif(a.firecomp IS NULL AND b.firecomp IS NOT NULL, true) as firecomp,
    count(nullif(a.policeprct IS NULL AND b.policeprct IS NOT NULL, true) as policeprct,
    count(nullif(a.healtharea IS NULL AND b.healtharea IS NOT NULL, true) as healtharea,
    count(nullif(a.sanitboro IS NULL AND b.sanitboro IS NOT NULL, true) as sanitboro,
    count(nullif(a.sanitsub IS NULL AND b.sanitsub IS NOT NULL, true) as sanitsub,
    count(nullif(a.address IS NULL AND b.address IS NOT NULL, true) as address,
    count(nullif(a.zonedist1 IS NULL AND b.zonedist1 IS NOT NULL, true) as zonedist1,
    count(nullif(a.zonedist2 IS NULL AND b.zonedist2 IS NOT NULL, true) as zonedist2,
    count(nullif(a.zonedist3 IS NULL AND b.zonedist3 IS NOT NULL, true) as zonedist3,
    count(nullif(a.zonedist4 IS NULL AND b.zonedist4 IS NOT NULL, true) as zonedist4,
    count(nullif(a.overlay1 IS NULL AND b.overlay1 IS NOT NULL, true) as overlay1,
    count(nullif(a.overlay2 IS NULL AND b.overlay2 IS NOT NULL, true) as overlay2,
    count(nullif(a.spdist1 IS NULL AND b.spdist1 IS NOT NULL, true) as spdist1,
    count(nullif(a.spdist2 IS NULL AND b.spdist2 IS NOT NULL, true) as spdist2,
    count(nullif(a.spdist3 IS NULL AND b.spdist3 IS NOT NULL, true) as spdist3,
    count(nullif(a.ltdheight IS NULL AND b.ltdheight IS NOT NULL, true) as ltdheight,
    count(nullif(a.splitzone IS NULL AND b.splitzone IS NOT NULL, true) as splitzone,
    count(nullif(a.bldgclass IS NULL AND b.bldgclass IS NOT NULL, true) as bldgclass,
    count(nullif(a.landuse IS NULL AND b.landuse IS NOT NULL, true) as landuse,
    count(nullif(a.easements IS NULL AND b.easements IS NOT NULL, true) as easements,
    count(nullif(a.ownertype IS NULL AND b.ownertype IS NOT NULL, true) as ownertype,
    count(nullif(a.ownername IS NULL AND b.ownername IS NOT NULL, true) as ownername,
    count(nullif(a.lotarea IS NULL AND b.lotarea IS NOT NULL, true) as lotarea,
    count(nullif(a.bldgarea IS NULL AND b.bldgarea IS NOT NULL, true) as bldgarea,
    count(nullif(a.comarea IS NULL AND b.comarea IS NOT NULL, true) as comarea,
    count(nullif(a.resarea IS NULL AND b.resarea IS NOT NULL, true) as resarea,
    count(nullif(a.officearea IS NULL AND b.officearea IS NOT NULL, true) as officearea,
    count(nullif(a.retailarea IS NULL AND b.retailarea IS NOT NULL, true) as retailarea,
    count(nullif(a.garagearea IS NULL AND b.garagearea IS NOT NULL, true) as garagearea,
    count(nullif(a.strgearea IS NULL AND b.strgearea IS NOT NULL, true) as strgearea,
    count(nullif(a.factryarea IS NULL AND b.factryarea IS NOT NULL, true) as factryarea,
    count(nullif(a.otherarea IS NULL AND b.otherarea IS NOT NULL, true) as otherarea,
    count(nullif(a.areasource IS NULL AND b.areasource IS NOT NULL, true) as areasource,
    count(nullif(a.numbldgs IS NULL AND b.numbldgs IS NOT NULL, true) as numbldgs,
    count(nullif(a.numfloors IS NULL AND b.numfloors IS NOT NULL, true) as numfloors,
    count(nullif(a.unitsres IS NULL AND b.unitsres IS NOT NULL, true) as unitsres,
    count(nullif(a.unitstotal IS NULL AND b.unitstotal IS NOT NULL, true) as unitstotal,
    count(nullif(a.lotfront IS NULL AND b.lotfront IS NOT NULL, true) as lotfront,
    count(nullif(a.lotdepth IS NULL AND b.lotdepth IS NOT NULL, true) as lotdepth,
    count(nullif(a.bldgfront IS NULL AND b.bldgfront IS NOT NULL, true) as bldgfront,
    count(nullif(a.bldgdepth IS NULL AND b.bldgdepth IS NOT NULL, true) as bldgdepth,
    count(nullif(a.ext IS NULL AND b.ext IS NOT NULL, true) as ext,
    count(nullif(a.proxcode IS NULL AND b.proxcode IS NOT NULL, true) as proxcode,
    count(nullif(a.irrlotcode IS NULL AND b.irrlotcode IS NOT NULL, true) as irrlotcode,
    count(nullif(a.lottype IS NULL AND b.lottype IS NOT NULL, true) as lottype,
    count(nullif(a.bsmtcode IS NULL AND b.bsmtcode IS NOT NULL, true) as bsmtcode,
    count(nullif(a.assessland IS NULL AND b.assessland IS NOT NULL, true) as assessland,
    count(nullif(a.assesstot IS NULL AND b.assesstot IS NOT NULL, true) as assesstot,
    count(nullif(a.exempttot IS NULL AND b.exempttot IS NOT NULL, true) as exempttot,
    count(nullif(a.yearbuilt IS NULL AND b.yearbuilt IS NOT NULL, true) as yearbuilt,
    count(nullif(a.yearalter1 IS NULL AND b.yearalter1 IS NOT NULL, true) as yearalter1,
    count(nullif(a.yearalter2 IS NULL AND b.yearalter2 IS NOT NULL, true) as yearalter2,
    count(nullif(a.histdist IS NULL AND b.histdist IS NOT NULL, true) as histdist,
    count(nullif(a.landmark IS NULL AND b.landmark IS NOT NULL, true) as landmark,
    count(nullif(a.builtfar IS NULL AND b.builtfar IS NOT NULL, true) as builtfar,
    count(nullif(a.residfar IS NULL AND b.residfar IS NOT NULL, true) as residfar,
    count(nullif(a.commfar IS NULL AND b.commfar IS NOT NULL, true) as commfar,
    count(nullif(a.facilfar IS NULL AND b.facilfar IS NOT NULL, true) as facilfar,
    count(nullif(a.borocode IS NULL AND b.borocode IS NOT NULL, true) as borocode,
    count(nullif(a.bbl IS NULL AND b.bbl IS NOT NULL, true) as bbl,
    count(nullif(a.condono IS NULL AND b.condono IS NOT NULL, true) as condono,
    count(nullif(a.tract2010 IS NULL AND b.tract2010 IS NOT NULL, true) as tract2010,
    count(nullif(a.xcoord IS NULL AND b.xcoord IS NOT NULL, true) as xcoord,
    count(nullif(a.ycoord IS NULL AND b.ycoord IS NOT NULL, true) as ycoord,
    count(nullif(a.longitude IS NULL AND b.longitude IS NOT NULL, true) as longitude,
    count(nullif(a.latitude IS NULL AND b.latitude IS NOT NULL, true) as latitude,
    count(nullif(a.zonemap IS NULL AND b.zonemap IS NOT NULL, true) as zonemap,
    count(nullif(a.zmcode IS NULL AND b.zmcode IS NOT NULL, true) as zmcode,
    count(nullif(a.sanborn IS NULL AND b.sanborn IS NOT NULL, true) as sanborn,
    count(nullif(a.taxmap IS NULL AND b.taxmap IS NOT NULL, true) as taxmap,
    count(nullif(a.edesignum IS NULL AND b.edesignum IS NOT NULL, true) as edesignum,
    count(nullif(a.appbbl IS NULL AND b.appbbl IS NOT NULL, true) as appbbl,
    count(nullif(a.appdate IS NULL AND b.appdate IS NOT NULL, true) as appdate,
    count(nullif(a.plutomapid IS NULL AND b.plutomapid IS NOT NULL, true) as plutomapid,
    count(nullif(a.version IS NULL AND b.version IS NOT NULL, true) as version,
    count(nullif(a.sanitdistrict IS NULL AND b.sanitdistrict IS NOT NULL, true) as sanitdistrict,
    count(nullif(a.healthcenterdistrict IS NULL AND b.healthcenterdistrict IS NOT NULL, true) as healthcenterdistrict,
    count(nullif(a.firm07_flag IS NULL AND b.firm07_flag IS NOT NULL, true) as firm07_flag,
    count(nullif(a.pfirm15_flag IS NULL AND b.pfirm15_flag IS NOT NULL, true) as pfirm15_flag
FROM dcp_pluto.:"VERSION" a
INNER JOIN dcp_pluto.:"VERSION_PREV" b
ON (a.bbl::bigint = b.bbl::bigint)
:CONDITION);