name: NumBldgs processing

on:
  issues:
    types: [opened, edited]

jobs:
  process_numbldgs:
    if: contains(github.event.issue.title, '[numbldgs]') && github.event.issue.author_association == 'CONTRIBUTOR'
    container:
      image: nycplanning/docker-geosupport:latest
    runs-on: self-hosted
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
    steps:
      - uses: actions/checkout@v2

      - name: get numbldgs
        working-directory: pluto_build/python
        run: python3 numbldgs.py

      - name: Comment on Issue and Close Issue
        if: success()
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## ${{ github.event.issue.title }} Is Successfully Updated! 🎉
            
            ### More Info
            for more details, check https://github.com/NYCPlanning/db-pluto/actions/runs/${{ github.run_id }}
          
          reactions: laugh, rocket, hooray
