name: CI

on: [push]

jobs:
  _01_dataloading:
    container:
      image: sptkl/cook:latest
    runs-on: self-hosted
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: ${{ secrets.BUILD_ENGINE }}
    steps:
      - uses: actions/checkout@v2
      - name: dataloading ...
        working-directory: pluto_build
        run: |
          python3 python/fastloading.py
  _02_build:
    needs: _01_dataloading
    container: 
      image: mdillon/postgis:latest
    runs-on: self-hosted
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: ${{ secrets.BUILD_ENGINE }}
      EDM_DATA: ${{ secrets.EDM_DATA }}
    steps:
      - uses: actions/checkout@v2
      - name: building...
        working-directory: pluto_build
        run: |
          ./02_build.sh | tee output/02_build.log
      - name: corrections
        shell: bash
        working-directory: pluto_build
        run: | 
          ./03_corrections.sh | tee output/03_corrections.log
      - name: archive
        shell: bash
        working-directory: pluto_build
        run: |
          ./04_archive.sh | tee output/04_archive.log
      - name: Upload build logs
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: pluto_build/output
  _03_export:
    needs: _02_build
    container: 
      image: mdillon/postgis:latest
    runs-on: self-hosted
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: ${{ secrets.BUILD_ENGINE }}
      EDM_DATA: ${{ secrets.EDM_DATA }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: create shapefile
        working-directory: pluto_build
        run: ./05_export.sh
  _04_qaqc:
    needs: _03_export
    container:
      image: sptkl/cook:latest
    runs-on: self-hosted
    env:
      EDM_DATA: ${{ secrets.EDM_DATA }}
    steps:
      - uses: actions/checkout@v2
      - name: qaqc ...
        working-directory: pluto_build
        run: |
          if [ -f version.env ]
          then
            export $(cat version.env | sed 's/#.*//g' | xargs)
          fi
          python3 python/qaqc/qaqc.py
