name: CI

on: [push]

jobs:
  skip:
    name: Build and test
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  _01_dataloading:
    needs: skip
    if: "! contains(github.event.head_commit.message, '[skip dataloading]')"
    container:
      image: sptkl/cook:latest
    runs-on: self-hosted
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: ${{ secrets.BUILD_ENGINE }}
    steps:
      - uses: actions/checkout@v2
      - name: dataloading ...
        working-directory: pluto_build
        run: |
          ./01_dataloading.sh
          python3 python/fastloading.py
  _02_build:
    needs: _01_dataloading
    container: 
      image: mdillon/postgis:latest
    runs-on: ubuntu-latest
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: ${{ secrets.BUILD_ENGINE }}
      EDM_DATA: ${{ secrets.EDM_DATA }}
    steps:
      - uses: actions/checkout@v2
      - name: building ...
        working-directory: pluto_build
        shell: bash
        if: "! contains(github.event.head_commit.message, '[skip build]')"
        run: |
          ./02_build.sh | tee output/02_build.log
          echo $?
      - name: part2
        working-directory: pluto_build
        shell: bash
        if: failure()
        run: |
          if [ -f version.env ]
          then
            export $(cat version.env | sed 's/#.*//g' | xargs)
          fi
          sleep 2m
          echo '\nPopulating PLUTO tags and version fields \e[32m'
          psql $BUILD_ENGINE -1 -f sql/plutomapid.sql
          psql $BUILD_ENGINE -1 -f sql/plutomapid_1.sql
          psql $BUILD_ENGINE -1 -f sql/plutomapid_2.sql
          psql $BUILD_ENGINE -1 -c "UPDATE pluto SET version = '$VERSION'"
          echo '\nBackfilling'
          psql $BUILD_ENGINE -1 -f sql/backfill.sql
      - name: corrections
        shell: bash
        working-directory: pluto_build
        if: "! contains(github.event.head_commit.message, '[skip build]')"
        run: | 
          ./03_corrections.sh | tee output/03_corrections.log
      - name: archive
        shell: bash
        working-directory: pluto_build
        if: "! contains(github.event.head_commit.message, '[skip archive]')"
        run: |
          ./04_archive.sh | tee output/04_archive.log
      - name: Upload build logs
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: pluto_build/output
  _03_export:
    needs: _02_build
    if: "! contains(github.event.head_commit.message, '[skip export]')"
    container: 
      image: mdillon/postgis:latest
    runs-on: self-hosted
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: ${{ secrets.BUILD_ENGINE }}
      EDM_DATA: ${{ secrets.EDM_DATA }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: create shapefile
        working-directory: pluto_build
        run: ./05_export.sh
  _04_qaqc:
    needs: _03_export
    if: "! contains(github.event.head_commit.message, '[skip qaqc]')"
    container:
      image: sptkl/cook:latest
    runs-on: self-hosted
    env:
      EDM_DATA: ${{ secrets.EDM_DATA }}
    steps:
      - uses: actions/checkout@v2
      - name: qaqc ...
        working-directory: pluto_build
        run: |
          if [ -f version.env ]
          then
            export $(cat version.env | sed 's/#.*//g' | xargs)
          fi
          python3 python/qaqc/qaqc.py
          exit 0
