name: Open Data Refresh
on:
  workflow_dispatch:


jobs:
  dataload:
    runs-on: ubuntu-20.04
    env:
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-recipes
    strategy:
      matrix:
        dataset:
          - dcp_cdboundaries_wi
          - dcp_cb2010_wi
          - dcp_ct2010_wi
          - dcp_cb2020_wi
          - dcp_ct2020_wi
          - dcp_school_districts
          - dcp_firecompanies
          - dcp_councildistricts_wi
          - dcp_healthareas
          - dcp_healthcenters
          - dcp_zoningmapindex
          - dpr_greenthumb
          - dsny_frequencies
          - lpc_historic_districts
          - lpc_landmarks
          - dof_dtm

    steps:
      - uses: actions/checkout@v2
      - uses: NYCPlanning/action-library-archive@v1.1
        with:
          name: ${{ matrix.dataset }}
          s3: true
          latest: true
          output_format: pgdump
